"""Design tokens — Qt port of ``lazygimp/gui/theme.py``.

Every color hex code below is copied VERBATIM from the Tk theme: this is
a toolkit swap, not a redesign. If you need to restyle the app, this is
still the one file to edit — page code (Tk or Qt) never hardcodes a
color or font tuple of its own.

Two extra things live here that the Tk version didn't need:

* ``qfont()`` — turns an ``F_*`` tuple into a ``QFont`` instance, since
  Qt widgets want font objects, not tuples, at the point of use.
* ``build_stylesheet()`` — a global QSS string applied once to the
  ``QApplication`` for chrome Qt renders itself (QScrollBar, QToolTip,
  the base QWidget palette, etc). Per-widget look (button variants, card
  borders, radii that vary per instance) is generated by
  ``lazygimp/gui/widgets.py`` itself, same division of labor as the
  Tk engine (theme.py = tokens, widgets.py = how they're used).
"""
from __future__ import annotations

from PySide6.QtGui import QColor, QFont

# --- dark palette (identical hex values to lazygimp/gui/theme.py) ---------
BG = "#1b1d21"
CARD_BG = "#26282e"
CARD_BORDER = "#35373e"
TEXT = "#e7e8ea"
TEXT_MUTED = "#9a9da4"
ACCENT = "#4dc3f0"
ACCENT_HOVER = "#6fd0f5"
ACCENT_TEXT = "#08222b"
SUCCESS = "#3fbf7f"
SUCCESS_HOVER = "#57cf93"
SUCCESS_TEXT = "#08210f"
DANGER = "#ee5a5f"
DANGER_HOVER = "#f27478"
DANGER_TEXT = "#2b0b0c"
WARNING = "#f2a93c"
DISABLED_BG = "#34363c"
DISABLED_TEXT = "#6d7076"

FIELD_BG = "#303237"          # line edits / combo boxes
SCROLLBAR = "#4a4d54"
LOG_BG = "#101114"            # install-progress log panel
SECONDARY_HOVER = "#3f424a"   # hover fill of secondary buttons

# tone colors for callouts / snackbars: tone -> (background, foreground)
TONE_COLORS = {
    "info": ("#16303a", "#7fd0f0"),
    "warn": ("#3a2e14", WARNING),
    "error": ("#3a1414", DANGER),
    "ok": ("#123522", SUCCESS),
}

# --- fonts ------------------------------------------------------------------
# Kept as the SAME (family, size, weight) tuples as the Tk theme so page
# code that already imports F_* names doesn't need to change shape, only
# import path. Use qfont(F_WHATEVER) to get a QFont when a Qt widget
# wants one.
FONT_FAMILY = "Sans"
F_HERO = (FONT_FAMILY, 30, "bold")          # landing title
F_H1 = (FONT_FAMILY, 21, "bold")            # screen titles
F_H2 = (FONT_FAMILY, 19, "bold")            # page headers
F_H3 = (FONT_FAMILY, 17, "bold")            # wizard step title
F_CARD_TITLE = (FONT_FAMILY, 15, "bold")
F_DIALOG_TITLE = (FONT_FAMILY, 14, "bold")
F_ITEM_TITLE = (FONT_FAMILY, 13, "bold")
F_SECTION = (FONT_FAMILY, 12, "bold")
F_SUBTITLE = (FONT_FAMILY, 12)
F_BODY_B = (FONT_FAMILY, 11, "bold")
F_BODY = (FONT_FAMILY, 11)
F_SMALL_B = (FONT_FAMILY, 10, "bold")
F_SMALL = (FONT_FAMILY, 10)
F_MONO = ("Monospace", 10)

# base size for the vector icons; call sites scale from here so the whole
# icon set can be grown/shrunk in one place
ICON_SIZE = 20


def qfont(spec) -> QFont:
    """(family, size[, weight]) -> QFont. The Qt-native counterpart of
    passing an F_* tuple straight to a Tk widget's font= kwarg."""
    family, size = spec[0], spec[1]
    weight = spec[2] if len(spec) > 2 else "normal"
    f = QFont(family, size)
    f.setBold(weight == "bold")
    return f


def qcolor(hexstr: str) -> QColor:
    return QColor(hexstr)


def build_stylesheet() -> str:
    """Global QSS applied once to the QApplication. Covers the chrome Qt
    draws itself (scrollbars, tooltips, the base window/widget palette,
    line edits, combo boxes) plus baseline rules for QPushButton "card"
    frames / QProgressBar / QCheckBox that widgets.py's per-instance
    stylesheets build on top of via more specific selectors.

    Per-instance colors (button variant, card hover/active border, which
    vary by construction args, not by class) are NOT here — see
    widgets.py's `_button_qss()` / `_card_qss()`. This mirrors the split
    in the Tk engine: theme.py owns tokens, widgets.py owns how a given
    instance of a widget uses them.
    """
    return f"""
    QWidget {{
        background-color: {BG};
        color: {TEXT};
        font-family: "{FONT_FAMILY}";
        font-size: 11pt;
        border: none;
    }}

    QMainWindow, QDialog {{
        background-color: {BG};
    }}

    QLabel {{
        background: transparent;
        border: none;
        color: {TEXT};
    }}

    QToolTip {{
        background-color: {CARD_BG};
        color: {TEXT};
        border: 1px solid {CARD_BORDER};
        padding: 4px 8px;
        border-radius: 6px;
    }}

    QLineEdit, QTextEdit, QPlainTextEdit {{
        background-color: {FIELD_BG};
        color: {TEXT};
        border: 1px solid {CARD_BORDER};
        border-radius: 8px;
        padding: 6px 10px;
        selection-background-color: {ACCENT};
        selection-color: {ACCENT_TEXT};
    }}
    QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {{
        border: 1px solid {ACCENT};
    }}
    QLineEdit:disabled {{
        background-color: {DISABLED_BG};
        color: {DISABLED_TEXT};
    }}

    QComboBox {{
        background-color: #282a30;
        color: {TEXT};
        border: 1.5px solid #4a4d5a;
        border-radius: 8px;
        padding: 6px 36px 6px 12px;
        font-weight: 600;
    }}
    QComboBox:hover {{
        background-color: #31343c;
        border: 1.5px solid {ACCENT};
    }}
    QComboBox:focus {{
        border: 1.5px solid {ACCENT};
    }}
    QComboBox::drop-down {{
        subcontrol-origin: padding;
        subcontrol-position: top right;
        width: 30px;
        border-left: 1px solid #4a4d5a;
        border-top-right-radius: 8px;
        border-bottom-right-radius: 8px;
        background: transparent;
    }}
    QComboBox::down-arrow {{
        image: none;
        border: none;
        width: 0;
        height: 0;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 6px solid {ACCENT};
        margin-right: 2px;
    }}
    QComboBox QAbstractItemView {{
        background-color: {CARD_BG};
        color: {TEXT};
        border: 1px solid {CARD_BORDER};
        border-radius: 8px;
        padding: 4px;
        selection-background-color: {ACCENT};
        selection-color: {ACCENT_TEXT};
        outline: none;
    }}

    QProgressBar {{
        background-color: {CARD_BORDER};
        border: none;
        border-radius: 4px;
        text-align: center;
        color: transparent;
    }}
    QProgressBar::chunk {{
        background-color: {ACCENT};
        border-radius: 4px;
    }}

    QCheckBox {{
        spacing: 8px;
        color: {TEXT_MUTED};
        background: transparent;
    }}
    QCheckBox::indicator {{
        width: 18px;
        height: 18px;
        border-radius: 6px;
        border: 2px solid {CARD_BORDER};
        background: transparent;
    }}
    QCheckBox::indicator:hover {{
        border: 2px solid {ACCENT_HOVER};
    }}
    QCheckBox::indicator:checked {{
        background-color: {ACCENT};
        border: 2px solid {ACCENT};
    }}

    QScrollArea {{
        background-color: {BG};
        border: none;
    }}
    QScrollArea > QWidget > QWidget {{
        background-color: {BG};
    }}

    QScrollBar:vertical {{
        background: transparent;
        width: 10px;
        margin: 2px;
    }}
    QScrollBar::handle:vertical {{
        background: {SCROLLBAR};
        border-radius: 4px;
        min-height: 24px;
    }}
    QScrollBar:vertical {{
        background: transparent;
        width: 10px;
        margin: 2px;
    }}
    QScrollBar::handle:vertical {{
        background: {SCROLLBAR};
        border-radius: 5px;
        min-height: 24px;
    }}
    QScrollBar::handle:vertical:hover {{
        background: #60646e;
    }}
    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
        height: 0px;
        background: transparent;
    }}
    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {{
        background: transparent;
    }}

    QScrollBar:horizontal {{
        background: transparent;
        height: 10px;
        margin: 2px;
    }}
    QScrollBar::handle:horizontal {{
        background: {SCROLLBAR};
        border-radius: 5px;
        min-width: 24px;
    }}
    QScrollBar::handle:horizontal:hover {{
        background: #60646e;
    }}
    QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
        width: 0px;
        background: transparent;
    }}
    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{
        background: transparent;
    }}
    """
